name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: subdir/go.sum

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get .
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Gosec Security Scanner
        run: make security

      - name: Build Go App
        run: make build
